version: '3'
services:
  app:
    
    build: .
    
    image: tedypristt/webacademy:latest
    container_name: webacademydemo
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production